### ISSUE TITLE
batch explorer stops refreshing info approx every 24 hours (must be restarted)

### ISSUE THREAD

**Issue by rfernand2** [Azure/BatchExplorer#2406]
**Describe the bug**
I'm running Batch explorer to monitor 1-2 jobs, each of which has between 100-200 nodes.  After about 24 hours, BE stops refreshing information - e.g., for the "pool" information, it shows no pools even though they are still running.  Clicking on refresh button on switching back and forth between tabs doesn't refresh the information.  I need to restart BE in order to get the information back.

**Expected behavior**
I expect BE to keep updating information no matter how long it is run.

**Screenshots**

**Logs(Click profile > View Logs > app.log, client.log)**
If applicable please attach those log files

**Version (please complete the following information):**
 - OS:  Windows 10 (20H2, Build 19042.1466)

**Comment by rfernand2** [comment]
I have noticed this red error box showing up in at least some of the above failing cases:
![image](https://user-images.githubusercontent.com/4296158/150694297-c9e7f5fa-576c-40bc-91de-6428afece941.png)

**Comment by dpwatrous** [comment]
This should be fixed by https://github.com/Azure/BatchExplorer/pull/2321 which was included in the most recent stable release.

**Comment by rfernand2** [comment]
Hi @dpwatrous, this is still broken in latest version of Batch Explorer.  In latest version (downloaded in last 1-3 days), after running for > 24 hours, it continually displayed animated circles that grow and shrink on various tabs, including Dashboard.  This goes on for at least 5 minutes.  If I restart, it prompts for credentials and then normal information is correctly displayed.
