### ISSUE TITLE
Heat Map display not accurate

### ISSUE THREAD

**Issue by abfleishman** [Azure/BatchExplorer#2500]
**Describe the bug**
The heatmap colors are not always correct.  in the attached screenshot only a single node was running and the rest were starting but two nodes appeared green which was incorrect and one of the green nodes was missing the hatching and had a little stripe of yellow at the top. 
![image](https://user-images.githubusercontent.com/9219852/166586977-200033dd-1dd8-40cd-b42c-f4be0bb1981f.png)
Here is a later screenshot showing the issue much more extensively
![image](https://user-images.githubusercontent.com/9219852/166587627-4bd644c6-e63e-4985-a0f7-e4dc090e7bcc.png)

**Version (please complete the following information):**
 - OS: [Windows/Osx/Linux] 
 Windows
 
 - Version [e.g. 0.15.2]

 2.13.0-stable.593

**Comment by gingi** [comment]
Hi there. We just fixed an issue related to how heatmaps are rendered (#2497). Can you install [the insider build](https://azure.github.io/BatchExplorer/insider.html) to see if this addresses your issue?

**Comment by abfleishman** [comment]
@gingi I am still having the same issue for the "running" tasks here version 2.14.0-insider.602
![image](https://user-images.githubusercontent.com/9219852/169101315-07d2f9a5-f15c-4fc0-bb42-5f887178afc5.png)

**Comment by gingi** [comment]
Thank you. We will look at this more closely.

**Comment by abfleishman** [comment]
Cool!  Looks like it is working as expected and I like the new colors for each sub category!
